/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author doanp
 */
public class ChaoDiaLog extends javax.swing.JDialog {

    /**
     * Creates new form ChaoDiaLog
     */
    public ChaoDiaLog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        init();
    }
    Timer tm;

    void init() {
        setSize(800, 400);
        setResizable(false);
        setLocationRelativeTo(null);
        tm = new Timer(1, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                int t = pgbLoading.getValue();
                t += 2;
                switch (t) {
                    case 20:
                        lblThongbao.setText("Chờ một chút để hệ thống khởi động...");
                        break;
                    case 40:
                        lblThongbao.setText("Nếu bạn gặp khó khăn gì khi sử dụng...");
                        break;
                    case 60:
                        lblThongbao.setText("Hãy liên hệ với chúng tôi...");
                        break;
                    case 80:
                        lblThongbao.setText("Chúng tôi sẽ phát triển hệ thống tốt nhất...");
                        break;
                    case 90:
                        lblThongbao.setText("Hệ thống đã sẵn sàng. Cảm ơn vì đã sử dụng!!");
                        break;
                    default:
                        break;
                }
                pgbLoading.setValue(t);
                if (t > 100) {
                    tm.stop();
                    dispose();
                }
            }
        });
        tm.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblThongbao = new javax.swing.JLabel();
        pgbLoading = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        lblBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lblThongbao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblThongbao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongbao.setText("Chào mừng bạn đến với hệ thống quản lý nhà hàng...");
        lblThongbao.setToolTipText("");
        lblThongbao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblThongbao);
        lblThongbao.setBounds(440, 300, 330, 30);
        getContentPane().add(pgbLoading);
        pgbLoading.setBounds(440, 330, 330, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/daubep.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 40, 280, 250);

        lblBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/LoginBG.jpg"))); // NOI18N
        getContentPane().add(lblBG);
        lblBG.setBounds(0, 0, 800, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChaoDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChaoDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChaoDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChaoDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChaoDiaLog dialog = new ChaoDiaLog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBG;
    private javax.swing.JLabel lblThongbao;
    private javax.swing.JProgressBar pgbLoading;
    // End of variables declaration//GEN-END:variables
}
